const Map<String, dynamic> IOB_CODES = {
  "330SA": 'SIM',
  "330SB": 'SIM',
  "330SC": 'SIM',
  "330SD": 'SIM',
  "330SE": 'SIM',
  "330SF": 'SIM',
  "737SA": 'SIM',
  "737SB": 'SIM',
  "737SC": 'SIM',
  "737SD": 'SIM',
  "737SE": 'SIM',
  "737SF": 'SIM',
  "787 HS1": 'STDBY',
  "787 HS2": 'STDBY',
  "787 HS3": 'STDBY',
  "787A": null,
  "787B": null,
  "A/L": 'LEAVE',
  "A1": null,
  "A2": null,
  "A310SD": 'SIM',
  "A33": null,
  "A330 DIF": null,
  "A330 FAM": 'FLIGHT',
  "A330TRNG": 'GROUND',
  "A330_CON": null,
  "AAS1": null,
  "AAS2": null,
  "ADM": 'GROUND',
  "ADM-A": 'GROUND',
  "ADM-D": 'GROUND',
  "ADM-N": 'GROUND',
  "AGC": null,
  "AHS1": 'STDBY',
  "AHS2": 'STDBY',
  "AHS3": 'STDBY',
  "AL/BM": 'LEAVE',
  "AL/OP": 'LEAVE',
  "AL/OPS": 'LEAVE',
  "AS1": 'STDBY',
  "AS2": 'STDBY',
  "AS3": 'STDBY',
  "AS4": 'STDBY',
  "AS5": 'STDBY',
  "AS6": 'STDBY',
  "AS7": 'STDBY',
  "ASM": 'STDBY',
  "ASSESS": null,
  "ATPL": null,
  "ATR": null,
  "ATR/SEP": null,
  "ATR/SNY": null,
  "AW": null,
  "B737": null,
  "B787A": null,
  "BC": null,
  "BMN": null,
  "BOFF": 'OFF',
  "BT": null,
  "BTR": null,
  "CAI TRNG": null,
  "CAT": null,
  "CBT": 'GROUND',
  "CBT INST": 'GROUND',
  "CBT_MAX": 'GROUND',
  "CCREF1": 'GROUND',
  "COFF": null,
  "COMP LVE": null,
  "COMPLVE2": null,
  "COMPLVE3": null,
  "CRM": 'GROUND',
  "CRM INST": 'GROUND',
  "CRMCON": 'GROUND',
  "CRMI": 'GROUND',
  "CRMIG": 'GROUND',
  "CRM_REM": 'GROUND',
  "CRM_TRG": 'GROUND',
  "CSSL": null,
  "D/T": null,
  "DE": null,
  "DEG": null,
  "DEM": null,
  "DFS TRG": 'GROUND',
  "DGR": 'GROUND',
  "DOFF": null,
  "DOH": null,
  "DT": null,
  "DTH LVE": null,
  "E/L": null,
  "EBT_COAC": null,
  "EBT_WS": null,
  "EHS1": 'STDBY',
  "EHS2": 'STDBY',
  "EHS3": 'STDBY',
  "ELP": null,
  "EMBR": null,
  "ERP": null,
  "ETO": null,
  "EXAM LVE": null,
  "FA": null,
  "FA INST": null,
  "FA-CC": null,
  "FAM A330": null,
  "FA_TRG": null,
  "FERRY": 'FLIGHT',
  "FF": null,
  "FIM": null,
  "FLMGMT": null,
  "FLT_TRA": null,
  "FOAI": null,
  "FOAP": null,
  "FTDSA": 'SIM',
  "FTDSB": 'SIM',
  "FTDSC": 'SIM',
  "FTDSD": 'SIM',
  "FTDSE": 'SIM',
  "FTDSF": 'SIM',
  "G/S": null,
  "GLB": null,
  "GLY TRNG": null,
  "GRD": null,
  "GRREF1": null,
  "GRREF2": null,
  "HAJ": null,
  "HHLV": null,
  "HRDOC": null,
  "HR_INV": null,
  "HS-AM": 'STDBY',
  "HS-PM": 'STDBY',
  "HS1": 'STDBY',
  "HS2": 'STDBY',
  "HS3": 'STDBY',
  "HS4": 'STDBY',
  "HS5": 'STDBY',
  "H_AND_S": null,
  "H_S": null,
  "IC": null,
  "IC INST": null,
  "IFC TRG": null,
  "IFE": null,
  "IND": null,
  "INST C": null,
  "INST CRM": null,
  "INSTR-C": null,
  "INT": null,
  "IOE": null,
  "IOS": null,
  "IPT TRG": null,
  "L/B": 'LEAVE',
  "L/REST": null,
  "LAY": null,
  "LB/BM": null,
  "LB/OP": null,
  "LB/OPS": null,
  "LC": null,
  "LHR": null,
  "LHR 1": null,
  "LHR SVC": null,
  "LIC": null,
  "LMCL": null,
  "LON SIM": null,
  "LP": null,
  "LP ": null,
  "LS": null,
  "LTC/METG": null,
  "LTG": null,
  "LVBM": null,
  "LVE": null,
  "LWP": null,
  "M/L": null,
  "MED": null,
  "MGC": null,
  "MIN/L": null,
  "MRG LVE": null,
  "MTG": null,
  "N/S": null,
  "NGC": null,
  "NO/DOC": null,
  "NOPS": 'NOPS',
  "NQ": null,
  "NQX": null,
  "OFF": 'OFF',
  "OFL": null,
  "OFLD": null,
  "OFLN": null,
  "OFLNX": null,
  "OFLX": null,
  "OIL": null,
  "ONDUTY": null,
  "OPS LVE": null,
  "OPS/LVE": null,
  "PC": null,
  "PDC": 'GROUND',
  "PDC330": 'GROUND',
  "PDC737": 'GROUND',
  "PDC787": 'GROUND',
  "PDCATR": 'GROUND',
  "PDCE170": 'GROUND',
  "PDO": null,
  "PER": null,
  "PFR": null,
  "PGC_REFR": null,
  "PH LVE": 'LEAVE',
  "PLWP": null,
  "PM": null,
  "PRAC330": null,
  "PRAC737": null,
  "PRAC787": null,
  "PRACA330": null,
  "PRACATR": null,
  "PRACB737": null,
  "PREG LVE": 'LEAVE',
  "PRM SVC": null,
  "PROMO": null,
  "PSY TEST": null,
  "REFUSAL": null,
  "RHS": null,
  "RNA": null,
  "ROF": 'OFF',
  "RQST LVE": 'LEAVE',
  "RSG": null,
  "RT": null,
  "RT737": null,
  "RTATR": null,
  "RVS": null,
  "SEC": 'GROUND',
  "SECI": null,
  "SEP EMJ": 'GROUND',
  "SEP310": 'GROUND',
  "SEP330": 'GROUND',
  "SEP330C": 'GROUND',
  "SEP330F": 'GROUND',
  "SEP330S": 'GROUND',
  "SEP737": 'GROUND',
  "SEP737I": 'GROUND',
  "SEP737S": 'GROUND',
  "SEP787": 'GROUND',
  "SEP787C": 'GROUND',
  "SEP788S": 'GROUND',
  "SEPA330": 'GROUND',
  "SEPATR": 'GROUND',
  "SEPATRC": 'GROUND',
  "SEPATR_C": 'GROUND',
  "SEPE170S": 'GROUND',
  "SEPEMBC": 'GROUND',
  "SEPPRAC": 'GROUND',
  "SFI": null,
  "SFS": null,
  "SFS TRNG": null,
  "SFS UG ": null,
  "SIC": null,
  "SICK": null,
  "SICK CO": null,
  "SICK LHR": null,
  "SICK LM": null,
  "SICK-IA": null,
  "SICK-NA": null,
  "SICK-OB": null,
  "SICKT": null,
  "SICKX": null,
  "SIM": 'SIM',
  "SIM1": 'SIM',
  "SIM1 F": 'SIM',
  "SIM1A": 'SIM',
  "SIM1B": 'SIM',
  "SIM1C": 'SIM',
  "SIM1D": 'SIM',
  "SIM1E": 'SIM',
  "SIM1F": 'SIM',
  "SIM1TLS": 'SIM',
  "SIM2": 'SIM',
  "SIM2A": 'SIM',
  "SIM2B": 'SIM',
  "SIM2C": 'SIM',
  "SIM2D": 'SIM',
  "SIM2E": 'SIM',
  "SIM3": 'SIM',
  "SIM4": 'SIM',
  "SIM5": 'SIM',
  "SIM6": 'SIM',
  "SIMA": 'SIM',
  "SIMERJ": 'SIM',
  "SIMSBY": 'SIM',
  "SIM_A": 'SIM',
  "SIM_EC": 'SIM',
  "SIM_ED": 'SIM',
  "SIV": null,
  "SNY DOC": null,
  "SOFF": null,
  "SOP": null,
  "SPCL LVE": null,
  "SPPRC330": null,
  "SPPRC737": null,
  "SPPRC787": null,
  "SPPRC788": null,
  "SPPRCATR": null,
  "SPPRCEMB": null,
  "ST": null,
  "STDY LVE": null,
  "STLC": null,
  "STR": null,
  "SUS": null,
  "SUSXPAY": null,
  "SVC": null,
  "SVCCON": null,
  "SVCI": null,
  "SYS": null,
  "SYS INST": null,
  "TBN": null,
  "TEC INST": 'GROUND',
  "TECREF1": 'GROUND',
  "TECREF2": 'GROUND',
  "TERMIN": null,
  "TMP A/L": null,
  "TRE LIC": null,
  "TRI LIC": null,
  "TSBY": null,
  "TTT": null,
  "TTT INST": null,
  "TVQ": null,
  "TVS HS1": 'STDBY',
  "TVS HS2": 'STDBY',
  "TVS HS3": 'STDBY',
  "TVS TRNG": null,
  "U/ABS": null,
  "U/C": null,
  "UNFIT": null,
  "VACC": null,
  "VIVA330": null,
  "VIVA737": null,
  "VIVA787": null,
  "VIVA788": null,
  "VIVAATR": null,
  "VIVAEMB": null,
  "VIVA_330": null,
  "VIVA_737": null,
  "W+TC INS": null,
  "WB": null,
  "WB INST": null,
  "WIT": null,
  "WOFF": null,
  "WRGT": null,
  "WRGTT1": null,
  "WRK SHP": null,
  "WRT": null,
  "WS": null,
  "WS INST": null,
  "XM/L": null,
  "XSICK": null,
  "ZFT": 'FLIGHT'
};
